// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Service.APIProduct.Data;

#nullable disable

namespace Restaurant.Service.APIProduct.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230614054818_AddDbProductModel")]
    partial class AddDbProductModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Service.APIProduct.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Pizza",
                            Description = "Nước, bột và men được để lên men từ 24 giờ trở lên. Nhào nặn thành những chiếc bánh tròn, dẹt rồi cho vào lò nướng chín. Loại bánh này siêu ngon ",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Pizza Hải Sản Pesto Xanh",
                            Price = 300000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Món Nướng",
                            Description = "Cá Chẽm Fillet Đút Lò Sốt Carri Chanh là món ăn đặc biệt làm say mê rất nhiều thực khách bởi hương vị chua chua, mặn mặn, thơm thơm từ chanh muối. Với công thức áp chảo chuyên nghiệp cùng nước sốt cà ri chanh muối lạ vị đã mang đến cho móng ăn được nhiều người yêu thích",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Cá Phile Đút Lò",
                            Price = 125000.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Món Chiên",
                            Description = "Mực có vị ngọt tự nhiên, dai dai được tẩm ướp gia vị và phủ lớp bột bên ngoài mang đén cảm giác giòn rụm và đậm đà cho người thưởng thức.",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "Mực chiên giòn",
                            Price = 85000.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Món chiên",
                            Description = "Chả giò hải sản giòn rụm với nhân hải sản gồm tôm, mực tươi ngon bên trong sẽ là món ăn khai vị hấp dẫn cho các bữa tiệc",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Chả giò hải sản",
                            Price = 72000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
